Update CI.yml with docker network

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,33 +1,49 @@
 name: CI
+
 on:
   push:
     branches: [ main ]
   pull_request:
     branches: [ main ]
   workflow_dispatch:
+
 jobs:
   build:
     runs-on: ubuntu-latest
-  
+
+    env:
+      TESTCONTAINER_DOCKER_NETWORK: tomodachi-testcontainers
+
     steps:
+      - uses: actions/checkout@v4
 
-      - uses: actions/checkout@v2
-
-      - name: Set up JDK 17
-        uses: actions/setup-java@v2
+      - name: Set up JDK 21
+        uses: actions/setup-java@v4
         with:
-          java-version: '17'
-          distribution: 'adopt'
+          java-version: '21'
+          distribution: 'temurin'
 
-      - name: Build Docker image for tests
-        run: docker compose -f docker-compose.dev.yml -f docker-compose.override.yml up --build -d
+      # Crear la red antes de los tests
+      - name: Create Docker network for Testcontainers
+        run: docker network create ${{ env.TESTCONTAINER_DOCKER_NETWORK }} || true
 
-      - name: Fix file permissions
-        run: sudo chown -R $USER:$USER .
+      # Build Docker image for tests (opcional)
+      - name: Build Docker image - Dev
+        run: docker compose -f docker-compose.dev.yml -f docker-compose.override.yml build
 
-      - name: Build and run tests with Gradle
-        run: ./gradlew build --no-daemon
+      # Levantar servicios para tests si necesitas (opcional)
+      - name: Start CI services
+        run: docker compose -f docker-compose.dev.yml -f docker-compose.override.yml up -d
 
+      # Ejecutar Gradle con tests de Testcontainers
+      - name: Build and run tests
+        run: ./gradlew clean build --no-daemon
+
+      # Apagar contenedores al final
+      - name: Stop Docker services
+        run: docker compose -f docker-compose.dev.yml -f docker-compose.override.yml down
+
+      # Cleanup Gradle cache
       - name: Cleanup Gradle Cache
         run: |
           rm -f ~/.gradle/caches/modules-2/modules-2.lock
